name: Lint and publish docker image
on: [push]
jobs:
  lint:
    name: Frontend lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
      - name: Install packages
        run: npm ci
      - name: Check linting rules
        run: npm run lint
      
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: lint
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
